dist: trusty
sudo: false
language: java

jdk:
  - openjdk7
  - oraclejdk8
env:
  global:
    secure: "bzuNxOqjQboSdu2S5uvViMwT5n3gJ6ieilaW4D+5lDsdYlpNiAkUtxgjU13a827589HNX0eUN24BQrdaHjLVR9tTFAUJEJiLFH/4bwEt24CCgfDLjSGoTW7fSpzikMim5ru2KGlimP0Mr0qNHLC0GLHGILK0773Eb8ddE53C7dlufDBxiOdO/vQDnsU6ii5cFoem5i74xSTNzJts7MmU4TJE9dTMY/3B/Rp3cZVQIGUPXgXeXSgpUH/fRBCFI06dQp0oJnzMjdz7YwolnFz+qIhBHF1qg719Wiy98EjvPkIEZ54NTjOYy1LI27vZh3djMQDL5s4cc8HyvkJkFBYuvltJui5rH1LzOumyO7vzxbClMjUE9Peb3lrE2hd5+//+fKqzcakW5DW9OysmOqlSPO9wgQGmc4H3drynsKerrfmqZBYyDgH9rGs5UVxXJBhzPQ4HGbbGPz7CT9yPbtx5kqBdO2g2V8JxaV0lMjA+3+gQ/mv9aHNSlYyRUDLsnT1tXnVBdfy4iQ+jpaDXwAYipGGqEBnLQgaC87Arp6TPNuTgQQRoPt4Y2nsGncc6Vtf7IIIJe4iwLSGW9NvGyCNBExTpUShbghyPgIiGr1v2lP6robXJZ07cRkhQOvdxBKTNLxbMnvVAKla+gyXLTaZEwKJqt36mVXOL+oH7oqLBVGk="  # BINTRAY_API_KEY

install:
  - mvn clean install -DskipTests=true
script:
  - mvn verify -B

before_cache:
  - rm -Rf $HOME/.m2/repository/cz/jirutka/spring/
cache:
  directories:
    - $HOME/.m2

deploy:
  # Deploy snapshots to Bintray.
  - provider: script
    script: mvn deploy --settings .maven-bintray.xml -Dgpg.skip=true -DskipTests=true
    skip_cleanup: true
    on:
      branch: master
      jdk: oraclejdk8
