dist: trusty
sudo: false
language: java

jdk:
  - openjdk7
  - oraclejdk8

before_cache:
  - rm -Rf $HOME/.m2/repository/cz/jirutka/spring/
cache:
  directories:
    - $HOME/.m2

install:
  - mvn clean install -DskipTests=true
script:
  - mvn verify -B
